/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'brand-teal': '#2bc7d0',
        'brand-teal-light': '#a6e9ed',
        'brand-cream': '#f8f5f0',
        'brand-terracotta': '#c46b48',
        'primary': '#031f41',
        'primary-container': '#1d3557',
        'on-primary': '#ffffff',
        'on-primary-container': '#879ec6',
        'inverse-primary': '#b0c7f1',
        'secondary': '#00696e',
        'on-secondary': '#ffffff',
        'secondary-container': '#68f3fc',
        'on-secondary-container': '#006e73',
        'surface': '#fcf9f4',
        'surface-dim': '#dcdad5',
        'surface-bright': '#fcf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ee',
        'surface-container': '#f0ede9',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#44474e',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f3f0eb',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-variant': '#e5e2dd',
        'background': '#fcf9f4',
        'on-background': '#1c1c19',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'tertiary': '#3e1000',
        'tertiary-container': '#601f02',
        'on-tertiary-container': '#e3845f',
      },
      fontFamily: {
        'display-lg': ['Barlow Condensed', 'sans-serif'],
        'display-lg-mobile': ['Barlow Condensed', 'sans-serif'],
        'headline-lg': ['Barlow Condensed', 'sans-serif'],
        'headline-md': ['Barlow Condensed', 'sans-serif'],
        'body-lg': ['Nunito Sans', 'sans-serif'],
        'body-md': ['Nunito Sans', 'sans-serif'],
        'label-md': ['Nunito Sans', 'sans-serif'],
        'caption': ['Nunito Sans', 'sans-serif'],
        'editorial': ['Cormorant Garamond', 'Georgia', 'serif'],
        'condensed': ['Barlow Condensed', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        'btn': '8px',
        'card': '16px',
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'base': '8px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'sidebar': '240px',
      },
      boxShadow: {
        'coastal': '0 4px 20px -2px rgba(29, 53, 87, 0.08)',
        'coastal-hover': '0 8px 30px -4px rgba(29, 53, 87, 0.12)',
      },
    },
  },
  plugins: [],
};
